language: go
install:
  - go get github.com/mozillazg/go-pinyin
  - go get github.com/mozillazg/go-pinyin/pinyin

script:
  - pinyin

notifications:
  email:
    on_success: change
    on_failure: always
