language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/mozillazg/go-pinyin
  - go get github.com/mozillazg/go-pinyin/pinyin

script:
  - pinyin
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email:
    on_success: change
    on_failure: always
